Repository Icaro-Salgado/w5g6-desafio-spring, pull requests merged in 2022-03, with the labels that each got.

#25 feat: add product model
  src/main/java/br/com/mercadolivre/desafiospring/models/Product.java
Labels: R01

#26 feat: add product service
  .gitmessage
  src/main/java/br/com/mercadolivre/desafiospring/repository/ApplicationRepository.java
  src/main/java/br/com/mercadolivre/desafiospring/services/ProductService.java
Labels: R01

#35 feat: add alphabetical ordering
  src/main/java/br/com/mercadolivre/desafiospring/controller/ProductController.java
  src/main/java/br/com/mercadolivre/desafiospring/services/ProductService.java
  src/main/java/br/com/mercadolivre/desafiospring/strategies/AlphabeticalSort.java
  src/main/java/br/com/mercadolivre/desafiospring/strategies/SortStrategy.java
Labels: R05

#41 feat: add price sort
  src/main/java/br/com/mercadolivre/desafiospring/services/ProductService.java
  src/main/java/br/com/mercadolivre/desafiospring/strategies/PriceSort.java
Labels: R06, R07

#91 Feat add inventory validation
  doc/documentacao_do_desafio/Desafio Spring.postman_collection.json
  doc/documentacao_do_desafio/LOG_REQUISITOS.md
  src/main/java/br/com/mercadolivre/desafiospring/controller/PurchaseController.java
  src/main/java/br/com/mercadolivre/desafiospring/controller/advice/DBExceptionHandler.java
  src/main/java/br/com/mercadolivre/desafiospring/exceptions/validations/OutOfStockException.java
  src/main/java/br/com/mercadolivre/desafiospring/services/PurchaseOperation.java
  src/main/java/br/com/mercadolivre/desafiospring/services/PurchaseService.java
Labels: R09
